steps:
- name: golang
  args: ['go', 'version']
- name: golang
  args: ['go', 'test']
  dir: 'backend'
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args: # https://cloud.google.com/sdk/gcloud/reference/functions/deploy
  - gcloud
  - functions
  - deploy
  - send-plex-invite
  - --region=us-central1
  - --source=backend
  - --trigger-http
  - --runtime=go121
  - --entry-point=SendInvite
  - --gen2
  - --allow-unauthenticated
  - --memory=128Mi
  - --set-secrets=PLEX_TOKEN=plex-token:latest,SLACK_WEBHOOK_URL=slack-webhook-url:latest
options:
  logging: CLOUD_LOGGING_ONLY
