steps:
- name: golang
  args: ['go', 'version']
- name: golang
  args: ['go', 'test']
  dir: 'backend'
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'send-invite', '--trigger-http', '--runtime', 'go116', '--entry-point', 'SendInvite']
  dir: 'backend'