steps:
- name: golang
  args: ['go', 'version']
- name: golang
  args: ['go', 'test']
  dir: 'backend'
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - send-plex-invite
  - --region=us-central1
  - --source=backend
  - --trigger-http
  - --runtime=go119
  - --entry-point=SendInvite
  - --gen2
  - --allow-unauthenticated
  - --memory=128MB
options:
  logging: CLOUD_LOGGING_ONLY
